using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace TemperatureForm
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)  //event generated by button click on the form 
        {
            ServiceReference1.Service1Client ob = new ServiceReference1.Service1Client();  //A service reference client object is created
            string a = textBox1.Text;  // textbox area holding the value of celsius temperature
            if (a != "")
            {
                int c = Int32.Parse(a);  // parsing the value of string to integer
                int q = ob.c2f(c);
                textBox2.Text = q.ToString(); // Converting the integer value to string
            }
            else
            {
                string b = textBox2.Text;  // textbox area holding the value of fahrenheit temperature
                int f = Int32.Parse(b);    // parsing the value of string to integer
                int r = ob.f2c(f);
                textBox1.Text = r.ToString(); // converting the integer value to string
            }
        }
    }
}